version: 2
updates:
  - package-ecosystem: "npm, docker, python, kubernetes" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
